#%RAML 1.0
title: MuleSoft IDP Platform API
mediaType: application/json
version: v1
protocols: [HTTPS]

baseUri: https://{anypointPlatformUri}/idp/api/{version}
baseUriParameters:
  anypointPlatformUri:
     description: MuleSoft Anypoint Platform Url
     default: "anypoint.mulesoft.com"
     enum: ["anypoint.mulesoft.com", "eu1.anypoint.mulesoft.com"]

uses:
  rest-connect: exchange_modules/org.mule.connectivity/rest-connect-library/1.0.2/rest-connect-library.raml

securedBy: [mulesoft-oauth_2_0, mulesoft-basic-login]
(rest-connect.userSelectedSecuritySchemes): User will select wich security scheme to use for this api.

traits:
  rateLimited:
    responses:
      429:
        description: |
          The client reached the maximum number of requests per minute per IP.
          The client should retry the request later.

/organizations:
  /{orgId}:
    uriParameters:
      orgId:
        type: field-orgId
        required: true
    /actions:
      get:
        displayName: IDP - Platform - Get Actions List
        queryParameters:
          page:
            type: number
            description: Zero Based
            default: 0
          size:
            type: number
            default: 20
          sort:
            type: string
            enum:
              - updatedAt,desc
              - updatedAt,asc
              - name,desc
              - name,asc
              - type,desc
              - type,asc
            default: updatedAt,desc
        responses:
          "200":
            body:
              type: object
      /{actionId}:
        uriParameters:
          actionId:
            type: field-actionId
            required: true
        get:
          displayName: IDP - Platform - Get Action Detail
          responses:
            "200":
              body:
                type: object
        /reviewers:
          get:
            displayName: IDP - Platform - Get Action's Reviewers List
            responses:
              "200":
                body:
                  items:
                    properties:
                      id:
                        example: 4d4fda9b-b772-4085-ac61-078af3b54543
                        type: string
                      name:
                        example: Composable Force
                        type: string
                      "type":
                        example: USER
                        type: string
                      email:
                        example: george@composableforce.com
                        type: string
        /versions:
          get:
            displayName: IDP - Platform - Get Action's Versions List
            responses:
              "200":
                body:
                  items:



securitySchemes:
  mulesoft-basic-login:
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: |
            Used to send username and password. Do not use
            with the "access_token" query string parameter.
          type: string
      responses:
        "200":
          body:
            application/json:
              properties:
                access_token:
                  example: d127e2ec-a703-4e2a-8629-e9158804748ble
                  type: string
                token_type:
                  example: bearer
                  type: string

  mulesoft-oauth_2_0:
    type: OAuth 2.0
    description: |
      OAuth2 is a protocol that lets external apps request authorization to private
      details in a user's account without getting their password. This is
      preferred over Basic Authentication because tokens can be limited to specific
      types of data, and can be revoked by users at any time.
      Use apiportal for the client_id
    settings:
      authorizationUri: 'https://{anypointPlatformUri}/accounts/api/v2/oauth2/authorize'
      accessTokenUri: 'https://{anypointPlatformUri}/accounts/api/v2/oauth2/token'
      authorizationGrants: [ authorization_code, implicit, client_credentials, password ]
#      authorizationGrants: [ authorization_code, implicit, client_credentials, password ]
    describedBy:
      responses:
        '401':
          description: |
            Bad or expired token. This can happen if the user or CloudHub
            revoked or expired an access token. To fix, you should re-
            authenticate the user.
        '403':
          description: |
            Bad OAuth request (wrong consumer key, bad nonce, expired
            timestamp...). Unfortunately, re-authenticating the user won't help here.
      headers:
        Authorization:
          description: |
            Used to send a valid OAuth 2 access token. Do not use
            with the "access_token" query string parameter.
          type: string
      queryParameters:
        access_token:
          description: |
            Used to send a valid OAuth 2 access token. Do not use together with
            the "Authorization" header
          type: string

types:
  field-orgId:
    description: |
      MuleSoft Anypoint Organization Id

      Your Anypoint Organisation Id see: [Find your Organization ID.](https://docs.mulesoft.com/access-management/organization#find-your-organization-id)
    example: eca25329-9592-4ff1-9054-1b08d103b991
    type: string
    pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"

  field-actionId:
    displayName: IDP Document Action Id
    description: Published Document Action UUID
    example: 90c3e286-72b5-42ca-92d0-22f86ea8d766
    type: string
    pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"

  field-actionVersion:
    displayName: IDP Document Action Id Version
    description: Document Action Version like 1.0.0
    example: 1.1.0
    type: string
    pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$

  field-executionId:
    displayName: IDP Execution Id
    description: IDP Execution Id returned after successful submission
    default: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
    example: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
    type: string
    pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"









