#%RAML 1.0
title: MuleSoft IDP Platform API
mediaType: application/json
version: v1
protocols: HTTPS


baseUri: https://anypoint.mulesoft.com/idp/api/{version}

securedBy:
  - mulesoft-basic-login

/organizations/{orgId}/actions:
  uriParameters:
    orgId:
      type: field-orgId
      required: true
  get:
    displayName: IDP - Platform - Get Actions List
    queryParameters:
      page:
        type: number
        description: Zero Based
        default: 0
      size:
        type: number
        default: 20
      sort:
        type: string
        enum:
          - updatedAt,desc
          - updatedAt,asc
          - name,desc
          - name,asc
          - type,desc
          - type,asc
        default: updatedAt,desc
    responses:
      "200":
        body:
          type: object
  /{actionId}:
    uriParameters:
      actionId:
        type: string
        required: true
    get:
      displayName: IDP - Platform - Get Action Detail
      responses:
        "200":
          body:
            type: object
    /reviewers:
      get:
        displayName: IDP - Platform - Get Action's Reviewers List
        responses:
          "200":
            body:
              items:
                properties:
                  id:
                    example: 4d4fda9b-b772-4085-ac61-078af3b54543
                    type: string
                  name:
                    example: Composable Force
                    type: string
                  "type":
                    example: USER
                    type: string
                  email:
                    example: george@composableforce.com
                    type: string
    /versions:
      get:
        displayName: IDP - Platform - Get Action's Versions List
        responses:
          "200":
            body:
              items:


securitySchemes:
  mulesoft-basic-login:
    type: Basic Authentication
    describedBy:
      responses:
        "200":
          body:
            application/json:
              properties:
                access_token:
                  example: d127e2ec-a703-4e2a-8629-e9158804748ble
                  type: string
                token_type:
                  example: bearer
                  type: string

types:
  field-orgId:
    description: |
      MuleSoft Anypoint Organization Id

      Your Anypoint Organisation Id see: [Find your Organization ID.](https://docs.mulesoft.com/access-management/organization#find-your-organization-id)
    example: eca25329-9592-4ff1-9054-1b08d103b991
    type: string
    pattern: "[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?"